#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions and clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
cleanCase
rm -f *pyc
rm -f *txt
rm -rf droploc
rm -f system/*txt
rm -rf prepp0 prepp1
cp 0/U.orig 0/U
cp 0/alpha.water.orig 0/alpha.water
cp 0/p_rgh.orig 0/p_rgh
cp system/controlDict.orig system/controlDict
#------------------------------------------------------------------------------
