#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean
runApplication blockMesh
runApplication setFields
runApplication $(getApplication)
#runApplication decomposePar
#runParallel $(getApplication)
#runApplication reconstructPar
runApplication foamToVTK
#paraFoam -builtin
#------------------------------------------------------------------------------
