#!/bin/bash
cd ${0%/*} || exit 1    # Run from this director

version=9
#dir_parent=$HOME/Programs/OpenFOAM/
dir_parent=/home/lihuiji2

rm -rf $dir_parent/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/dynamicMotion
cp -r dynamicMotion $dir_parent/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions

rm -rf $dir_parent/OpenFOAM-$version/applications/solvers/multiphase/raindropFoam
cp -r raindropFoam_v$version $dir_parent/OpenFOAM-$version/applications/solvers/multiphase/raindropFoam

cp dynamicFvMesh.H $dir_parent/OpenFOAM-$version/src/dynamicFvMesh/dynamicFvMesh/dynamicFvMesh.H

cp dynamicMotionSolverFvMesh.H $dir_parent/OpenFOAM-$version/src/dynamicFvMesh/dynamicMotionSolverFvMesh/dynamicMotionSolverFvMesh.H
cp dynamicMotionSolverFvMesh.C $dir_parent/OpenFOAM-$version/src/dynamicFvMesh/dynamicMotionSolverFvMesh/dynamicMotionSolverFvMesh.C

cp motionSolver.C $dir_parent/OpenFOAM-$version/src/dynamicMesh/motionSolvers/motionSolver/motionSolver.C
cp motionSolver.H $dir_parent/OpenFOAM-$version/src/dynamicMesh/motionSolvers/motionSolver/motionSolver.H
    
cp solidBodyMotionSolver.H $dir_parent/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionSolver/solidBodyMotionSolver.H
cp solidBodyMotionSolver.C $dir_parent/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionSolver/solidBodyMotionSolver.C

cp solidBodyMotionFunction.H $dir_parent/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunction.H

cp dynamicMeshFiles $dir_parent/OpenFOAM-$version/src/dynamicMesh/Make/files

cd $dir_parent/OpenFOAM-9
source etc/bashrc
./Allwmake -j > log.Allwmake
