#!/bin/bash
cd ${0%/*} || exit 1    # Run from this director

version=9
rm -rf $HOME/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/dynamicMotion
cp -r dynamicMotion $HOME/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions

rm -rf $HOME/OpenFOAM-$version/applications/solvers/multiphase/raindropFoam
cp -r raindropFoam_v$version $HOME/OpenFOAM-$version/applications/solvers/multiphase/raindropFoam

cp dynamicFvMesh.H $HOME/OpenFOAM-$version/src/dynamicFvMesh/dynamicFvMesh/dynamicFvMesh.H

cp dynamicMotionSolverFvMesh.H $HOME/OpenFOAM-$version/src/dynamicFvMesh/dynamicMotionSolverFvMesh/dynamicMotionSolverFvMesh.H
cp dynamicMotionSolverFvMesh.C $HOME/OpenFOAM-$version/src/dynamicFvMesh/dynamicMotionSolverFvMesh/dynamicMotionSolverFvMesh.C

cp motionSolver.C $HOME/OpenFOAM-$version/src/dynamicMesh/motionSolvers/motionSolver/motionSolver.C
cp motionSolver.H $HOME/OpenFOAM-$version/src/dynamicMesh/motionSolvers/motionSolver/motionSolver.H
    
cp solidBodyMotionSolver.H $HOME/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionSolver/solidBodyMotionSolver.H
cp solidBodyMotionSolver.C $HOME/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionSolver/solidBodyMotionSolver.C

cp solidBodyMotionFunction.H $HOME/OpenFOAM-$version/src/dynamicMesh/motionSolvers/displacement/solidBody/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunction.H

cp dynamicMeshFiles $HOME/OpenFOAM-$version/src/dynamicMesh/Make/files

cd $HOME/OpenFOAM-9
source etc/bashrc
./Allwmake -j > log.Allwmake